# Generated by Django 2.2.6 on 2019-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_text',
            field=models.TextField(null=True),
        ),
    ]
