# Generated by Django 2.2.6 on 2019-10-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20191027_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_text',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
