# Generated by Django 2.2.6 on 2019-11-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20191101_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
