# Generated by Django 2.2.6 on 2019-11-12 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20191112_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
