# Generated by Django 2.2.6 on 2019-11-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20191123_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_data',
            options={'verbose_name_plural': 'Users_Data'},
        ),
    ]
