# Generated by Django 2.2.6 on 2019-11-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20191123_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='user',
        ),
    ]
