# Generated by Django 2.2.6 on 2019-11-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_auto_20191124_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='city',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='pin',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='state',
            new_name='qualification',
        ),
    ]
