# Generated by Django 2.2.6 on 2019-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_auto_20191130_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
